const { webkit } = require('playwright-core');
const path = require('path');
(async () => {
  const exe = path.join(process.env.LOCALAPPDATA, 'ms-playwright', 'webkit-2336', 'Playwright.exe');
  const b = await webkit.launch({ executablePath: exe });
  const ctx = await b.newContext({ viewport: { width: 390, height: 844 }, deviceScaleFactor: 2, isMobile: true, hasTouch: true, reducedMotion: 'no-preference',
    userAgent: 'Mozilla/5.0 (iPhone; CPU iPhone OS 17_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.0 Mobile/15E148 Safari/604.1' });
  const p = await ctx.newPage();
  const logs = [];
  p.on('console', m => m.type() === 'error' && logs.push(m.text()));
  p.on('pageerror', e => logs.push('pageerror ' + e.message));
  await p.goto('http://localhost:5181/');
  await p.evaluate(() => localStorage.clear());
  await p.reload();
  await p.waitForTimeout(2500);
  await p.screenshot({ path: 'shots/wk-1-help.png' });
  await p.getByText('はじめる').click();
  await p.waitForTimeout(10600);
  await p.screenshot({ path: 'shots/wk-2-hatch.png' });
  await p.getByText('やったね').click();
  await p.locator('.name-input').fill('ぴよすけ');
  await p.getByText('これにする').click();
  await p.evaluate(() => { const g = window.__mini; const s = g.getState(); g.setState({ coins: 1000, pet: { ...s.pet, poops: 2, hunger: 20 } }); });
  await p.waitForTimeout(600);
  await p.screenshot({ path: 'shots/wk-3-home.png' });
  await p.getByLabel('おでかけ').click();
  await p.locator('.place', { hasText: 'はらっぱ' }).click();
  await p.waitForTimeout(400);
  await p.locator('.run-stage').tap();
  await p.waitForTimeout(1500);
  await p.screenshot({ path: 'shots/wk-5-run.png' });
  await p.waitForSelector('.run-cover.is-end', { timeout: 15000 });
  await p.getByRole('button', { name: 'かえる', exact: true }).click();
  await p.getByLabel('うんどう').click();
  await p.waitForTimeout(3000);
  await p.screenshot({ path: 'shots/wk-4-ex.png' });
  await p.getByLabel('おわる').click();
  console.log('state', await p.evaluate(() => { const s = window.__mini.getState(); return JSON.stringify({ reps: s.pet.reps, coins: s.coins, wearing: s.wearing, outings: s.outings.n }); }), 'ready', await p.evaluate(() => window.__miniReady));
  console.log('LOGS', logs.length ? logs.join('\n') : 'none');
  await b.close();
})();
